jondot/awesome-react-native

README.md
Link to the latest release on Facebook's React Native Github page was broken.
Now fixed.
=> Fix broken link for latest react-native release on Github

README.md
A `<Hyperlink />` component for react-native that makes urls, fuzzy links, emails etc clickable and stylable
=> add react-native-hyperlink

README.md
- Added `react-native-fit-image` to README.md
- React Native Fit Image enables you to draw responsive image component.
- Removed invaild url from README.md
- maybe http://tadeuzagallo.com/blog/react-native-bridge has broken.
=> Add react-native-fit-image to README.md

README.md
[react-native-incall-manager](https://github.com/zxcpoiu/react-native-incall-manager)
Handling media-routes/sensors/events during a audio/video chat like webrtc
=> add: react-native-incall-manager to Media category

README.md
react-router-native [[npm]](https://www.npmjs.com/package/react-router-native)
From the README:
> React Router community decided that a [reducer-based paradigm](https://github.com/reactjs/react-router/issues/743) similar to that of **NavigationExperimental** is better suited to native navigation. Transition to a reducer-based paradigm is also being [discussed](https://github.com/reactjs/react-router/issues/3190) for the web. On the other hand, NavigationExperimental [has no intention to support ](https://github.com/ericvicenti/navigation-rfc/issues/64#issuecomment-209001717) a React Router-like interface and leaves the navigation state up to the developer to maintain.
> 
> A declarative API removes the need to write [boilerplate code](https://github.com/facebook/react-native/commit/1dc33b5 …
=> Add react-router-native

README.md
This module was aiming to solving the issue facebook/react-native#854 , and it becomes an alternative to react-native-fs which has more features that fs does not have, for example file stream support, blob data upload and download. I hope it can be added to the list 😃
=> Add react-native-fetch-blob

README.md
We wrote a hands-on tutorial on test driving react native apps. We believe it goes well with rest of the content in this repo.
=> Add link to test driving react native applications tutorial

Gemfile, Gemfile.lock, dedup.rb, validate.rb
* Removes `nokogiri` from build and replaces it with a stdlib `REXML` implementation
* Fixes http status of link validator not affecting results
`dedup.rb` runs in about the same time, but without `nokogiri` installation time
```
ambp:awesome-react-native andrew$ time bundle exec ruby dedup.rb
Deduping 652 links...
Done.
real  0m0.738s
user  0m0.663s
sys   0m0.071s
ambp:awesome-react-native andrew$ time bundle exec ruby dedupv2.rb
Deduping 652 links...
Done.
real  0m0.875s
user  0m0.798s
sys   0m0.073s
```
`validate.rb` now properly flags links that return a 4xx status code, also no more `nokogiri`
```
ambp:awesome-react-native andrew$ time bundle exec ruby validate.rb
Validating 652 links...
.................................................................................................. …
```
=> Improves travis build process and validator accuracy

README.md
There is only a 7 month old readme and license file in the repo https://github.com/spikef/react-native-ajax
=> remove react-native-ajax

README.md
Add link to https://github.com/exponentjs/ex-navigation:
> A route-centric, batteries-included navigation library for Exponent and React Native that works seamlessly on Android and iOS.
Thanks for the awesome project!
=> Add ex-navigation to UI section

README.md
Hi,
I would like to suggest a "frequent" bloggers sections to be added to the list of resources. People interested in staying up-to-date with the latest news and tips&tricks provided by developer blogs can simply add the blogs to their RSS readers.
A separation could be made between official blogs and community driven blogs (developer blogs).
Kind Regards
Ruben
=> Add bloggers section to list of React Native resources

README.md, validate.rb
this is a very handy tools for android/React-native developers in case they are having problem with ADB's crashing problem while they are developing/testing/debugging with an actual device like me.
this will save alot of times.
=> add ADB-auto-restarter && Fix travis validation

README.md
The one mentioned currently is a fork for the original one.
=> Add link to original react-native-progress

README.md
Repo changed hands. Stars need updating too, but looks like that's done by a script.
=> Update URL for react-native-mock

README.md
Allows people to see touches and drags on app demo videos:
=> Add React Native Touch Visualizer

README.md
A React Native fork of the SSDP protocol node implementation to find plug and play devices in the network
=> Adds react-native-ssdp

README.md
Hey team!
I would love to add [react-native-gl-model-view](https://github.com/rastapasta/react-native-gl-model-view) to the list!
Main features:
* Display, rotate, scale and translate any textured 3D object!
* Animate with blasting fast 60FPS by using the [Animated API](https://facebook.github.io/react-native/docs/animations.html#using-the-native-driver) native driver
* Load any Wavefront .OBJ or GLEssentials model
* Use all texture image formats supported by [UIImage](https://developer.apple.com/library/content/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/LoadingImages/LoadingImages.html#//apple_ref/doc/uid/TP40010156-CH17-SW8)
=> Add react-native-gl-model-view

README.md
Fingerprint android auth for react-native (Android only).
This is an expandable Android fingerprint API compatible lib, which also combines Samsung and MeiZu's official Fingerprint API.
=> add react-native-fingerprint-identify

README.md
Simple skeleton loader for react native.
It displays lines and shapes on the screen (with optional animations) before state is ready, and then renders the concerned child component.
Example on here : https://github.com/Skahrz/rn-placeholder
EDIT: Example folder added with android and iOS
=> Add rn-placeholder

README.md
Hi! Today I published react-native-focus-scroll.
It can detect which children are focused when scrolling.
https://github.com/c-bata/react-native-focus-scroll
| Vertical Scrolling | Horizontal Scrolling |
|------------------|---------------------|
| ![sample - vertical](https://github.com/c-bata/react-native-focus-scroll/raw/master/example/anim.gif) |  ![sample - horizontal](https://github.com/c-bata/react-native-focus-scroll/raw/master/example/anim-horizontal.gif) |
I think this is useful in various applications. I'm so happy if many people use this library.
Thanks.
=> Add react-native-focus-scroll

README.md
One of the main issues of react-native-video is making video full-screen on Android. To solve this issue, I've made this package that acts as a full-screen video component.
=> added react-native-fullscreen-video under Media category

README.md
Cross-platform simple dialogs for React Native based on the Modal component.
Github: https://github.com/douglasjunior/react-native-simple-dialogs
=> Added react-native-simple-dialogs

README.md
Hello, 
I wrote a little component that will stay at the bottom of the screen and autogrow when text input is more that it could show - with an optional character counter on the right side (like on Twitter).
🍺
=> Add react-native-writebox to the list of components

README.md
1. `react-native-drawer` was moved to new location : https://github.com/root-two/react-native-drawer
2. Added `react-native-ui-kitten` into the UI list of components
@jondot
=> Added react-native-ui-kitten and updated react-native-drawer url and stars.

README.md
Adds a reference to the react-native-bundle-visualizer utility. The bundle visualizer is useful for isolating imported packages that increase your bundle size considerably (and sometimes unexpectedly) (e.g. when importing a big monolithic library)
=> Adds react-native-bundle-visualizer

README.md
Google renamed api.ai to dialogflow so I'd named my package as well
=> rename react-native-api-ai to react-native-dialogflow and update stars

README.md
👬 👭 Poor intrusive way to make A/B Testing by using an HoC instead of components
- Adding rn-ab-hoc
- Removing old school (but always existing on NPM) `react-native-ab-hoc`
=> Adding rn-ab-hoc

README.md
Adding Buttercup (for mobile) - an open-source password manager (that has an electron desktop counterpart).
Website: [buttercup.pw](https://buttercup.pw)
=> Add Buttercup mobile

README.md
Added react-native-open-maps, a simplified lib to handle opening of maps per coordinates, within the UI section.. let me know if you feel it should be moved to tools or geolocation.
=> Add react-native-open-maps to UI

README.md
Hi @jondot 
This is with reference to issue: [546](https://github.com/jondot/awesome-react-native/issues/546). I have created below RN Bridge Plugin Libraries for Android & iOS Platform  App Tour
- [react-native-taptargetview](https://github.com/prscX/react-native-taptargetview)
- [react-native-material-showcase-ios](https://github.com/prscX/react-native-material-showcase-ios)
Hope it might be useful for folks looking for nice, cool library for App Tour on RN
Can you please merge the raised request, please let me know in case any discussion is required for the same
Thanks
Pranav
=> Added ReactNative Bridge Plugin Library for Android & iOS App Tour

validate.rb
e.g. you can test by validating the last 15 links by adding this code in line 26 of `validate.rb`.
(before `puts "Validating #{links.size} links..."`)
```
links = links.last(15)
```
output:
```
$ bundle exec ruby validate.rb
Validating 15 links...
.S.............%
```
=> fix(build): skip udemy links validation if they return 403 http status

README.md
Hey guys,
I moved [react-native-scalable-image](https://github.com/ihor/react-native-scalable-image) into the section it belongs to.
=> Move react-native-scalable-image from System to UI section

README.md
Adding my image Higher Order Component package. It decorates the native Image component (thus can be used as drop in replacement) to add caching and permanent persistence functionality.
=> Adding react native image cache hoc.

README.md
We have a package that is the only one to allow uploading of files on iOS and Android in the background.  So if you background the app, the upload continues.  That's not the case with most other uploaders.  We humbly submit it to your list.
=> Add react-native-background-upload package

README.md
This is a react-native link library project for in-app purchase for both android and ios platforms. The goal of this project is to have similar experience between the two platforms for in-app-purchase.
=> Add react-native-iap

README.md
Spectrum decided to remove their mobile app from the repository (for now).
[https://github.com/withspectrum/spectrum/commit/4be7b7fe4248bf3b8071d507fe18a227a022a4c1](https://github.com/withspectrum/spectrum/commit/4be7b7fe4248bf3b8071d507fe18a227a022a4c1)
=> Remove Spectrum from open source apps

README.md
Add [react-native-flurry-sdk](https://github.com/flurry/react-native-flurry-sdk) to the list.
I also noted that there's also a [react-native-flurry](https://github.com/amitkothari/react-native-flurry) in the list. This repo is outdated and not actively maintained, but I'm not sure if it's proper to remove it from the list.
=> Add react-native-flurry-sdk

README.md
Added an awesome library for React Native which uses OkHttp 3 on Android, and AFNetworking on iOS
=> adding react-native-ssl-pinning

README.md
I have :
- added **react-native-referrer** ([https://github.com/JeandeCampredon/react-native-referrer](https://github.com/JeandeCampredon/react-native-referrer)) : React Native android only library to retrieve campaign referrer
- applied the contributing guideline.
- replaced Github broken link by NPM link
- removed libraries that can't be found anymore
=> Add react-native-referrer

README.md
react-native-vannila - Build universal cross-platform apps with React Native. Includes latest `iOS`, `tvOS`, `Android`, `Android TV`, `Android Wear`, `Web`, `Tizen TV`, `Tizen Watch`, `LG webOS`, `macOS/OSX`, `Windows` and `KaiOS` platforms
https://github.com/pavjacko/react-native-vanilla
=> add react-native-vannila

README.md
Hi @jondot thanks for your helpful repository.
I added [react-native-today-widget](https://github.com/matejkriz/react-native-today-widget) library.
I don't know why there is not this repository here.
Additionally, I added extension category and move [react-native-android-widget-poc](https://github.com/netbeast/react-native-android-widget-poc) library from tutorial category to extension category.
thanks.
=> Add extension category and react-native-today-widget

README.md
I would like to add my article on how to use React Native with TypeScript. [(It was encouraged by the RN team.)](https://twitter.com/reactnative/status/1093515749493227521)
[Using React Native With TypeScript](https://medium.com/@jan.hesters/using-typescript-with-react-native-946aa4b4ae6f)
=> Add 'Using React Native With TypeScript'

README.md
react-native-il8n has been deprecated for react-native-localize and react-native-languages has been renamed to react-native-localize.
=> Updated Internationalization

README.md
This PR adds the [Square React Native plugin](https://github.com/square/in-app-payments-react-native-plugin) for [Square In-App Payments SDK](https://squareup.com/developers/in-app-payments).
=> Add Square In-App Payments SDK

README.md
This PR adds the [**Real time Messaging**](https://github.com/agoraio/agora-react-native-rtm) React Native plugin for [**Agora RTM SDK**](https://docs.agora.io/en/Real-time-Messaging/RTM_product?platform=All%20Platforms).
=> add agora-react-native-rtm

README.md
Add a link to a fastlane beta build documentation and upgrade boilerplate list for TheCodingMachine react-native-boilerplate
https://github.com/thecodingmachine/react-native-boilerplate
https://github.com/thecodingmachine/react-native-boilerplate/blob/master/docs/beta%20builds.md
=> Add fastlane beta build documentation

README.md
Add `react-native-markdown-display` and move existing libs to the **Rich content** part.
Search for "Markdown"
=> Update Markdown related libs

README.md
`react-native-media-clipboard` lets you get an image the user has copied to the clipboard. 
Repo: https://github.com/Jarred-Sumner/react-native-media-clipboard
=> Add react-native-media-clipboard to the readme

README.md
[Source code](https://github.com/PedroBern/react-native-art-museums-app)
[Google Play link](https://play.google.com/store/apps/details?id=museum.art&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1)
This app use [Harvard Art Museum API](https://github.com/harvardartmuseums/api-docs) to let you browse through the art collection.
=> Add Art Museum to Open Source Apps

README.md
[react-native-use-persist-storage](https://github.com/visuallylab/react-native-use-persist-storage)
An easy way use persist storage using react hooks.
- persist storage([Async Storage](https://github.com/react-native-community/react-native-async-storage))
- easy use for react hooks
- support migration & sensitive info
=> Add react-native-use-persist-storage

README.md
Added a sample project built using TensorFlow.js and Expo (React Native). `tfjs` recently released an alpha version of adapters for React Native.
Source: https://github.com/t73liu/tfjs-starter
Blog: https://t73liu.github.io/posts/experimenting-with-tfjs/
Expo Preview: https://expo.io/@t73liu/tfjs-starter
=> Add TensorFlow.js starter app

README.md
React-native-sqlite should be removed from awesome-react-native. It is a duplicate and is no longer maintained. The react-Native-sqlite repo just points to react-native-sqlite-storage, which is already listed.
From the first line of the react-native-sqlite README:
"NOTE: This hasn't been maintained for a while and was never very complete to start with. Check out https://github.com/andpor/react-native-sqlite-storage for a more usable library!".
=> Removing [react-native-sqlite] (https://github.com/almost/react-native-sqlite) - SQLite3 bindings for React Native

README.md
Here I've added another one native-based Intercom implementation for React Native. Here is the [link](https://github.com/mateioprea/react-native-intercom).
=> add intercom native

README.md
I created an open source library for setting up "Rating System" in your mobile app. 
It supports:
decimal point ratings, direction aware like bottom to top or RTL etc, custom icons and images and record ratings given by user.
[react-native-rating-element](https://github.com/ui-ninja/react-native-rating-element)
Thank you 🙏🏻
=> Adding react-native-rating-element in list

README.md
Tiny component for cutting out click-through holes in any view.
Demo:
=> Add `react-native-hole-view`
