jondot/awesome-react-native

README.md
I used "my" master branch to create this PR without your merge, because I've correct just a typo
=> Added react-canvas and Flipboard article about

README.md
Added example of buyscreen which we made with our team to test react-native
=> added new example

README.md
Hi, we extracted carousel component from our example, may be it will be useful for somebody ;)
=> added react-native-looped-carousel

README.md
=> adds NewsWatch example app

README.md
Egghead.io: React Native Fundamentals Series
=> Added video tutorial link

README.md
Example React Native app using the Confreaks API.
=> Add Confreaks example app

README.md
Hey @jondot.
I added a component I just wrote to your component list.
=> add react-native-progress-hud to component list

README.md
I've added another example application to the examples list.
The app basically demonstrates how you can implement the Flux pattern (Alt) in React Native, making your codebase even more modular!
The app is simple: type in a location, and get a list of the most recent tweets for that location.
You can check out the repo [here](https://github.com/mrblueblue/react-native-alt-demo)
=> Update README with Alt/Flux example

README.md
=> Split Utilities into Utils and Seeds, and add more seeds

README.md
=> Add a layout component

CONTRIBUTING.md
:+1: I am open to suggestions and changes :facepunch:
=> #26 - add contributing.md

README.md
Thanks for maintaining this list. I recently put together [an app](appsto.re/us/NdeV7.i) ([source](https://github.com/jhabdas/lumpen-radio)) and an article I'd like to add. The app is [well](http://slides.com/jhabdas/streaming-audio-react-native/) [documented](www.oreilly.com/pub/e/3483) and is useful for those looking to build streaming audio apps. While I was in there I made a few other enhancements to make the content easier to read and conform with contrib guidelines.
=> Add an example, an article, a component and update formatting

README.md
And thanks for the CI approach, I have a blog with years worth of links, gotta find that bitrot somehow.
=> Provide short summary for react-native-snippets

README.md
And stuff. Please see commit comments for details. Thanks!
=> Updating list of awesomely awesome things

README.md
(for when you need more than a webview, adds back/forward/refresh, etc)
=> add react-native-browser

README.md
The module is developed by me.
=> Add WebRTC module

README.md
=> Fix typo in description of autoresponsive package

README.md
http://microsoft.github.io/code-push/
=> Add CodePush

README.md
Adding Text To Speech Engine Module for Android.
=> Added React-native-android-speech

README.md
https://github.com/apolkingg8/React-Native-Swipeable-Modal does not exist
=> Removed react-native swipable modal as it does not exist

README.md
React Native seed written in Typescript
=> add React Native with Typescript seed

README.md
<image src="https://media.giphy.com/media/t2wkSkgNI5QMo/giphy.gif" width="100px">
Add https://github.com/plrthink/react-native-zip-archive
=> Add Unzip archive utility

README.md
I've released an 𝐎𝐩𝐞𝐧 𝐒𝐨𝐮𝐫𝐜𝐞 𝐒𝐨𝐟𝐭𝐰𝐚𝐫𝐞 project I call 𝑺𝒏𝒐𝒘𝒇𝒍𝒂𝒌𝒆. It's a javascript based application for both iOS and Android Devices. It is written using 𝗥𝗲𝗮𝗰𝘁𝗡𝗮𝘁𝗶𝘃𝗲, 𝗣𝗮𝗿𝘀𝗲.𝗰𝗼𝗺, 𝗥𝗲𝗱𝘂𝘅, 𝗝𝗲𝘀𝘁, 𝗜𝗺𝗺𝘂𝘁𝗮𝗯𝗹𝗲, and other technologies. This release it to help other developers learn how these 𝘁𝗲𝗰𝗵𝗻𝗼𝗹𝗼𝗴𝗶𝗲𝘀 𝘄𝗼𝗿𝗸 𝘀𝗲𝗮𝗺𝗹𝗲𝘀𝘀𝗹𝘆 𝘁𝗼𝗴𝗲𝘁𝗵𝗲𝗿 and take what used to be incredibly difficult to now be very achievable. I would consider it at this time as a "𝗯𝗼𝗶𝗹𝗲𝗿𝗽𝗹𝗮𝘁𝗲" or "𝘀𝘁𝗮𝗿𝘁𝗲𝗿" project that developers can learn from and use as their starting point
=> Add Snowflake

README.md
* Add react-native-hot-redux-starter
* Sort items in list
=> Add react-native-hot-redux-starter

README.md
I added a section for libraries related to styling react native apps.  Included my own library, Cairn, as well as React Native CSS.
=> New section for libraries related to styling

README.md
I would like to add react-native-timepicker library, which can be used as 24hours timepicker.
=> Add react-native-timepicker

README.md
first beacon library to work cross-platform
=> add link to react-native-discovery

README.md
=> add react-native-extended-stylesheet

README.md
404 https://github.com/manandmoon/react-native-swiper/
404 https://github.com/exponentjs/babel-preset-react-native
=> Remove deleted projects

README.md
Text Blast includes analogous [React Native](https://github.com/SeshApp/text-blast-react-native) and [Ionic](https://github.com/SeshApp/text-blast-ionic) client implementations which should be useful to Ionic developers considering React Native and vice-versa.
=> Add text blast to example apps

README.md
updated how many stars the repo(react-native-aws-signature) has
=> updated how many stars the repo has

README.md
The old socket.io guide didn't actually work that well, for the reasons that I've outline in the new guide I wrote.
=> Adding feathers to the mix and an updated react native socket.io guide

README.md
These are two of my libraries.Let me know if there is anything missing.
=> Added react-native-signalr and react-native-device-log

README.md
- react.parts moved to js.coach
New UI components:
- react-native-modal-picker
- react-native-webbrowser
- react-native-multiple-choice
=> Update react.parts url to new project page and add 3 new components

README.md
Messaging Platform SendBird(https://sendbird.com) React Native Version Sample Code.
=> Added SendBirdReactNativeSample

README.md
We've reached 128 stars in the last few days, yay!
We've also created a new repo that simplifies the API
=> Updated stars for react-native-controllers and added react-native-navigation

README.md
a library to report the device compass heading back to your react native app
=> Add link to react-native-heading

README.md
=> adding new article

README.md
Health Trainer & User Connection Application Example
=> adding Hello Bemans Example

README.md
Check user permissions from react native
=> added link to react-native-permissions

README.md
I add the library [react-native-nav](https://github.com/jineshshah36/react-native-nav) which is a cross-platform (iOS / Android), fully customizable, React Native navigation bar component that will work well with flux or redux
=> add react-native-nav

README.md
Really awesome course that helped me out a lot. You can get it extremely cheap ($15) with a coupon code too.
=> Add video link for Udemy course

README.md
you use react native more, the more native parts you will touch.
Need more advanced articles about this part.
=> More article about native component

README.md
=> add insta snap link

README.md
A simple react-native picker component written in ES6
=> Add react-native-simple-picker

README.md
add wordpress based article reader built with react native for android
=> add ziliun react native

README.md
Added Reactotron, which is instrumentation and control from your terminal. See https://twitter.com/skellock/status/722680834063495169.
=> Add Reactotron by Steve Kellock

README.md
add react-native-html-parser
This make you can use parse html in react-native
=> Add react-native-html-parser in utils

README.html, README.md
=> add Reddit example app

README.md
A set of native Android UI components and modules for React Native framework.
=> Added react-native-android-kit

README.md
A React Native date, datetime and time picker for both Android and IOS
=> add react-native-datepicker

README.md
- Modify react-navtive-fit-image star count
=> Modify react-navtive-fit-image stars

README.md
A React Native component providing images selection from camera roll.
=> react-native-camera-roll-picker

README.md
I'm adding the photo gallery component that i've recently published.
Thanks for the great list.
=> add react-native-photo-browser

README.md
Hi,
I just wrote this component and want to add it to the list.
Thanks! :)
=> Add react-native-bar-collapsible

README.md
Add a new Checkbox component for both Android and iOS! Thanks!
=> Add react-native-custom-checkbox.

README.md
It's unfinished, and I'm still not enough time to complete it, so it is not suitable to appear here. :)
=> Remove whirlyglobe

README.md
* Add two AWS S3 solutions to `Backend`.
* The `react-native-aws-s3` is still unfinished long time, so I recommend to remove it.
=> Add AWS S3 solutions, and remove unfinished solution

README.md
Country picker provides a modal allowing a user to select a country from a list. It display a flag next to each country name.
=> Add react-native-country-picker-modal

README.md
Add a link to react-native-sketch in the 'UI' section.
=> Add react-native-sketch

README.md
update readme with react-native-custom-segmented-control
=> Add custom segmented control

README.md
- Modify react-navtive-fit-image star count
=> Modify react-native-fit-image star count

README.md
=> Add react-native-debugger

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jondot/awesome-react-native/181)
=> +react-native-fxblurview: wrap FXBlurView for better blurs

README.md
[react-native-voip-push-notification](https://github.com/ianlin/react-native-voip-push-notification)
iOS prioritized VoIP Push Notification
=> add: react-native-voip-push-notification to System category

README.md
- New category: `Monetization` .
- Added `react-native-revmob`.
=> Add Monetization category and react-native-revmob

README.md
Follow some activities (new user, payment, ...) from your app via Slack and this webhook lib
And change number of star in react-native-country-picker-modal.
Thanks.
=> Add react-native-slack-webhook please :)

README.md
A brand new framework to help generate apps, screens, components and more...
=> add ignite to frameworks

README.md
Added React Weather to examples sections
=> Added another example to the example section: a weather app built using React Native

README.md
I added an Utils and fixed some links without https://
=> Add react-native-babel-jest and fix some links

README.md
Add NYTimesTopStories-React-Native
=> Add NYTimesTopStories-React-Native

README.md
=> Add react-native-sglistview

README.md
I removed duplicate "ignite" link to pass travis-ci test. Thanks!
=> Remove duplicate "ignite" link

README.md
add the react-native-picker-xg
=> feature(location): add react-native-picker-xg

README.md
simple emoji picker for react native
=> react-native-emoji-picker

README.md
Please add react-native-stripe-api
=> Please add react-native-stripe-api

README.md
@bkspace thought you might be interested to know I submitted this PR.
=> Added Redux + Facebook Auth examle

README.md
Adding a nice react native lib to navigate: react-native-router-flux and a wrapper of it that uses mobx.
=> Add react-native-router-flux and react-native-mobx

README.md
Added my app to the list of examples
=> added NBAreact to list of examples

README.md
Tutorial that uses Django backend api to comment on a central chatlist for both platforms + Web.
=> Add tutorial example for using Django backend with react-native

README.md
Adding my RN project 😁 https://github.com/cheeaun/hackerweb-native
=> Add HackerWeb into Examples section

README.md
React Native Forms is a library I've been been writing and using in production recently, and just open sourced.  Would you be interested in adding it to the list?
=> Can I add react-native-forms?

README.md
Awesome realm should be there.
=> Add link to realm

README.md
This is an iOS & Android react native module to play an audio stream, with background support and media controls.
- Android version based on the work of @EstebanFuentealba https://github.com/EstebanFuentealba/react-native-android-audio-streaming-aac
- iOS version based on the work of @jhabdas https://github.com/jhabdas/lumpen-radio
=> Add react-native-audio-streaming module

README.md
Added react-native-responsive module
=> react-native-responsive 

README.md
add How to add Firebase Auth with react native article in Article of How to
=> add How to add Firebase Auth with react native

README.md
[React-Native-Router-Sinux](https://github.com/jbpin/react-native-router-sinux) allow you to easly use NavigationExperimental in your project. It use [Sinux](https://github.com/jbpin/sinux) as Flux implementation.
=> Added react-native-router-sinux

README.md
https://kylewbanks.com/blog/react-native-tutorial-part-1-hello-react
=> Adding a Calculator app tutorial for Android and iOS

README.md
point react-native-svg to the maintained repo
=> update react-native-svg link

README.md
Added the component [react-native-off-canvas-menu](https://github.com/shoumma/react-native-off-canvas-menu)
=> Added an UI component

README.md
=> add react-native-device-angles

README.md
Highly customizable calendar datepicker. [Github Repo]( https://github.com/vlad-doru/react-native-calendar-datepicker)
=> Added a new calendar datepicker component.

README.md
I have made some changes to https://github.com/mrpatiwi/ReactNativeTS, so I would like to update the description.
=> Update description of React Native Typescript

README.md
=> Add react-native-credit-card-input

README.md
=> Add article for previewing RN apps on Github Pull Request

README.md
a multi select like select2 on web with full example
=> added react-native-multi-select

README.md
Adding a new, fully customizable Navbar component for React-Native
=> adding navbar-native UI component

README.md
=> Add react-native-elements

README.md
[react-native-modal-dropdown ★15](https://github.com/sohobloo/react-native-modal-dropdown) - A react-native dropdown/picker/selector component for both Android & iOS.
=> Add react-native-modal-dropdown

README.md
i just received this cool repo from one slack channel , i thought its good to share it here ;)
=> background service and web worker

README.md
Here's a cool open source project. A clone version of the Facebook basketball game.
=> Add react-native-basketball

README.md
[React Native Progressive Input](https://github.com/khaiql/react-native-progressive-input) is a text input control which has clear text button and activity indicator, usually used as input source of autocomplete control.
=> add react-native-progressive-input

README.md
I'm excited for React Native specific conferences!
=> Adding conferences!

README.md
react-native-foldview [[github]](https://github.com/jmurzy/react-native-foldview) [[npm]](https://www.npmjs.com/package/react-native-foldview)
Thanks!
🍺
=> add react-native-foldview

README.md
Update react-native-fit-image star count
- `40` => `63`
=> Update react-native-fit-image star count

README.md
Adding popup menu UI component.
=> added react-native-popup-menu

README.md
- highlight the difference between this repo and the already existing react-native-twilio
=> Add link to react-native-twilio-programmable-voice

README.md
https://twitter.com/ChainReactConf/status/800744311209897984
=> Added dates and city to Chain React Conf

README.md
A new link to "https://www.smashingmagazine.com/2016/04/the-beauty-of-react-native-building-your-first-ios-app-with-javascript-part-1/" which gives a step-by-step walk-through for building a wallpaper app. Very helpful for beginners.
=> Added a new link in tutorials

README.md
Hey! I've added one more open source application.
=> Add react-native-qrcode-app to OS apps

README.md
=> add react-native-qqsdk

README.md
=> add react-native-color-picker

README.md
Short-term memory training game. Done with RN adn Redux. Free, no ads, open source.
https://github.com/sobstel/sequent
=> Add Sequent game

README.md
As stated [here](https://github.com/futurice/pepperoni-app-kit/blob/master/docs/AUTH0.md)
=> Pepperoni no longer includes auth

README.md
iOS 10 **CallKit** framework for React Native
=> Add react-native-callkit to System section

README.md
Add [Instabug](https://instabug.com/) SDK to intergrations
=> Add instabug-reactnative' to readme

README.md
It's a component for grading scores using ReactART.
=> add react-native-grading

README.md
Now that developing React Native applications for Windows is possible I wrote a quick article on getting people set up.
=> Added link to follow-up article

README.md
GITHUB - https://github.com/24ark/react-native-step-indicator
NPM - https://www.npmjs.com/package/react-native-step-indicator
=> Adding react-native-step-indicator

README.md
Basically did a search for all navigation and put in it's own category considering how core it is to development.
- Added https://github.com/react-community/react-navigation
- Merged Routing with Navigation for sanity.
Future pulls may continue to segment components like awesome-swift (https://github.com/matteocrippa/awesome-swift)
=> Updated README.md - Adding Navigation Category

README.md
TvOS remote controller module for react native.
=> Add react-native-tvos-controller

README.md
Add react-native-drawer-menu and update other two components.
=> Add react-native-drawer-menu Component

README.md
Good channel with a series about react native in spanish.
=> Add Mario Díez youtube channel and Remove 404 links

README.md
https://github.com/shahen94/react-native-video-processing
=> Add react-native-video-processing

README.md
https://github.com/oblador/react-native-animatable
=> Add react-native-animatable

README.md
From 15 to 102.
Thanks for all the starers!
=> Update stars for react-native-modal-dropdown

README.md
https://github.com/charlesvinette/react-native-haptic
=> Add react-native-haptic

README.md
=> Added an app to the list of open source projects

README.md
https://github.com/madriska/react-native-quick-actions
=> Add react-native-quick-actions

README.md
add react-native-expand component
=> add react-native-expand component

README.md
Please add!
https://github.com/williamtran29/react-native-ibeacon-simulator
Thank you
=> Add react-native-ibeacon-simulator

README.md
Please add!
https://github.com/noradaiko/pouchdb-adapter-react-native-sqlite
=> Add pouchdb-adapter-react-native-sqlite

README.md
https://github.com/noradaiko/react-native-sqlite-2
Thanks for maintaining great curated list!
=> Add react-native-sqlite-2

README.md
=> add react-native-card-media

README.md
Hope it's not weird that I added my own Medium profile to this 😆. I write a lot about React Native.
=> Blogs Update

README.md
Though it's against the guidelines in contributing I added two links - they're relevant to each other though so I'm hoping it's okay.
Will break into two PRs if necessary!
=> Add Navigation tutorials

README.md
=> Update stars of react-native-super-grid

README.md
[eact-native-parallax-scroll-view](https://github.com/jaysoo/react-native-parallax-scroll-view) - A ScrollView-like component with parallax and sticky header support.
=> Add react-native-parallax-scroll-view module

README.md
Add [react-native-interactable](https://github.com/wix/react-native-interactable)
not sure if it's correct section or not.
React-native-interactable is about animation, though
=> Add react-native-interactable

README.md
Haul is a command line tool for developing React Native apps -https://github.com/callstack-io/haul
=> Add Haul project

README.md
Added ASOS app built as a learning experience
Updated ★★ count for UrbanDictionary
=> Added ASOS

README.md
A complete tinder-like swiper component that supports stacking
=> Add react-native-swiper-animated

README.md
A comprehensive walkthrough of setting up fastlane for React Native on
both iOS and Android
=> Add React Native Training Medium article on fastlane

README.md
This adds two courses to the list. 
_Full disclosure_:  These courses are mine and I have a financial incentive associated with the sale of either of them. I think they're great courses (slightly biased 😃) and they've helped hundreds learn RN already but I completely understand if you don't want to list these. @jondot if you want to review either/both of them let me know and I'll add you to them so you can see if it makes sense for people looking at this list.
Also I tacked on a 50% off coupon for the Udemy course 😄
=> Add 2 Courses

README.md
This a floating action button(FAB) component for react native, works on both Android and iOS, and designed as per material design specs.
=> Add react-native-fab

README.md
Completily worth it for production-ready apps
=> Add react-native-exception-handler

README.md
Auto typing text component for react-native
=> Add react-native-auto-typing-text

README.md
Add rn-sliding-up-panel to UI section.
=> Add rn-sliding-up-panel

README.md
Add react-native-in-app-notification to UI section
=> Add react-native-in-app-notification

README.md
- ✅ Search previous suggestions before making a new one, as yours may be a duplicate.
- ✅ Suggested packages should be tested and documented.
- ✅ Make an individual pull request for each suggestion.
- ✅ Use the following format: [PACKAGE](LINK) - DESCRIPTION.
- ✅ New categories, or improvements to the existing categorization are welcome.
- ✅ Keep descriptions short and simple, but descriptive.
- ✅ End all descriptions with a full stop/period.
- ✅ Check your spelling and grammar.
- ✅ Make sure your text editor is set to remove trailing whitespace.
=> Add react-native-masonry to UI.Components

README.md
This adds [glamorous-native](https://github.com/robinpowered/glamorous-native) to the **Styling** section
=> Add glamorous-native

README.md
Add Wheel Picker for Android that include Date picker and Time picker
https://github.com/ElekenAgency/ReactNativeWheelPicker
=> Add react-native-wheel-picker-android

README.md
Add react-native-beautiful-image, react-native-beautiful-video-recorder, react-native-compress, react-native-thumbnail
=> Add react-native-beautiful-image, react-native-beautiful-video-recorder, react-native-compress, react-native-thumbnail

README.md
react-native-aws-cognito-js: This is an adaptation of Amazon Cognito Identity SDK for JavaScript in combination with AWS SDK for JavaScript for React Native.
=> add react-native-aws-cognito-js + update stars of react-native-cognito

README.md
Adding stars on [rn-placeholder](https://github.com/Skahrz/rn-placeholder)
=> Adding stars on rn-placeholder

README.md
Introducing a new A/B testing library that aims to be less intrusive than component based A/B testing using HoC
https://github.com/mfrachet/react-native-ab-hoc
=> Adding react-native-ab-hoc

README.md
A simple to follow video series in Arabic showing you how to build a newspaper app with React Native.
=> React Native video series in Arabic

README.md
Storybook makes it really easy to develop pure UI components, interactively.
=> Added Storybook in Utilities

README.md
Github: https://github.com/douglasjunior/react-native-keyboard-manager
Npm: https://www.npmjs.com/package/react-native-keyboard-manager
=> Added react-native-keyboard-manager

README.md
🔬 Image intent receiver for React Native android
=> Added react native image intent

README.md
Added react-native-search-box into the UI list of components
=> Added react-native-search-box

README.md
DuckDuckGo App in React-Native. (Unofficial)  https://github.com/kiok46/duckduckgo
=> Added - DuckDuckGo App (Unofficial)

README.md
react-native-api-ai is a react-native bridge for google's api.ai.
With api.ai you can design conversational apps based on voice or text.
=> add api.ai integration

README.md
Added "react-native-pagination" under UI section
=> Updated README.md-Added "react-native-pagination"

README.md
Much much faster and convenient than react-native-cached-image
=> Added an awesome FastImage component

README.md
formik a new rising react forms library with 2k stars.
[Formik is 100% compatible with React Native and React Native Web.](https://github.com/jaredpalmer/formik#react-native)
=> Added formik, Forms in React, without tears.

README.md
1. Algolia instant search integration library.
source: https://github.com/algolia/react-instantsearch
info: https://community.algolia.com/react-instantsearch
2. Fixed url that was moved to new location and caused build failures, this should resolve broken builds in:
- https://github.com/jondot/awesome-react-native/pull/499
- https://github.com/jondot/awesome-react-native/pull/500
- https://github.com/jondot/awesome-react-native/pull/501
- https://github.com/jondot/awesome-react-native/pull/503
- https://github.com/jondot/awesome-react-native/pull/504
- https://github.com/jondot/awesome-react-native/pull/506
3. Updated star count for : https://github.com/halilb/react-native-textinput-effects
4. Fixed featherjs client url that was no longer accessible (reason: HTTP redirects too deep). …
=> Added react native algolia instant search integration library.

README.md
Seeds: Added react-native-web-boilerplate and react-native-web-workspace
=> Open Source Apps: Added live translator

README.md
=> Add react-native-parallax-swiper

README.md
Add react-native-animated-check-mark to UI list in Readme
=> Add react-native-animated-check-mark

README.md
Add [`react-native-nfc-ios`](https://github.com/barodeur/react-native-nfc-ios) to README, the repo is documented and tested.
=> Add react-native-nfc-ios

README.md
Adds a link to react-native-ux-cam, thanks in advance!
=> [Analytics] Add react-native-ux-cam link + description

README.md
Add a new Udemy.com course: Automate Your React Native Releases with Fastlane & Bitrise.
=> Add Udemy course: React Native with Fastlane & Bitrise

README.md
Makeicon is a tool, that generates mobile app icons in all resolutions for both iOS and Android.
=> Add beplus/makeicon

README.md
This article has a list of top React Native libraries that I use in my apps. The libraries are explained along with practical demos and videos.
=> Added a new article featuring top libraries

README.md
=> rn-placeholder

README.md
npmjs.com/package/react-native-markdown-editor
=> Add react-native-markdown-editor

README.md
A course to build a weather app in react native
=> A course to build a weather app

README.md
An error tracking tool that works well with react native & has a free tier
=> Add BugSnag to Utilities

README.md
Add native-starter-kit to seeds section
=> Add native-starter-kit

README.md
Adding library which simplifies animating a `View`, `Image`, `Text` component between two styles, depending on the parent's state.  A good example of this is text that is red during an error, or a child view that moves or changes sizes/rotation depending on the state of the parent.
Library: https://github.com/EricPKerr/react-native-animated-styles
Before:
```
<Animated.View
style={{
width: 100,
height: 100,
opacity: animationValue.interpolate({
inputRange: [0, 1],
outputRange: [0, 1]
}},
transform: [
{rotate: animationValue.interpolate({
inputRange: [0, 1],
outputRange: ['0deg', '90deg']
})}
]
}}
/>
```
After:
```
<AnimatedStyles.View
style={{
width: 100,
height: 100,
opacity: 0
}}
animatedStyle={{
opacity: 1,
transform: [{ rotate: '90deg' }]
}}
active={this.state.active}
/>
```
=> Add AnimatedStyles library

README.md
add https://github.com/innFactory/react-native-quick-sample
>  A small and simple example app with navigation, data persistence, redux, listview and animation
update starts of react-native-api-ai
=> add quick sample app

README.md
Add [React Native Actions](https://github.com/lucasbento/react-native-actions).
https://github.com/lucasbento/react-native-actions
=> Add React Native Actions

README.md
https://github.com/BhavanPatel/react-native-easy-checkbox for easy and simple checkbox
and
https://github.com/BhavanPatel/react-native-simple-encryption for simple encryption
=> Added Two Modules

README.md
add react-native-scalable-image
https://github.com/ihor/react-native-scalable-image
> React Native Image component which scales width or height automatically to keep the original aspect ratio.
=> add scalable image

README.md
A native toast plugin added to dictionary
=> adding toast plugin

README.md
Reusable module with examples https://github.com/netbeast/react-native-color-wheel
=> Add react-native-color-wheel

README.md
- Add `react-native-background-fetch`
=> Add react-native-background-fetch

README.md
- Add new Section "Geolocation"
- Move other geolocation-related libs to new Section
- Add `react-native-background-geolocation`
=> Add react-native-background-geolocation.

README.md
This is a performant qrcode-generated library.
=> Add `react-native-qrcode-svg`

README.md
Stars on [`rn-placeholder`](https://github.com/mfrachet/rn-placeholder) and a quicklink to its dedicated gitbook https://mfrachet.github.io/rn-placeholder/
=> Stars rn-placeholder + gitbook

README.md
Added [react-native-track-player](https://github.com/react-native-kit/react-native-track-player). A module that we've been working in the last 6 months.
=> Added react-native-track-player

README.md
An tutorial / proof of concept on how to create Android Widgets in React Native (finally 🎉 )
Solution to https://stackoverflow.com/questions/33085364/is-it-possible-to-create-home-screen-widgets-for-android-using-ionic-framework-o/47025986#47025986
and
https://stackoverflow.com/questions/44258218/triggering-react-native-events-from-widget-android/47025974#47025974
=> Android Widget Proof of Concept

README.md
React Native Grid List component
=> Add react-native-grid-list

README.md
http://www.electrode.io/site/native.html
https://github.com/electrode-io/electrode-native
=> Add Electrode Native to utilities sections

README.md
In my opinion, this is the best audio recording library for react native right now.
=> Add react-native-sound-recorder

README.md
Added npm package react-native-fused-location inside Geolocation.
=> react-native-fused-location

README.md
I made functional modal component 
It allows developer to do many thing with this module I think
thank you
=> Update .md file (react-native-awesome-alert)

README.md
⚡️ 🌀 Measure React rendering lifecycles using controls
=> Adding rn-render-perfs

README.md
=> Add react-native-seed

README.md
A framework to test a React Native app during runtime and production.
More: https://github.com/netbeast/react-native-diagnose
=> Add React Native Diagnose

README.md
A React-Native utility belt for scaling the size your apps UI across different sized devices.
=> Added react-native-size-matters

README.md
Added react-native-interactive-image-gallery
Added react-native-incall-manager
=> Added react-native-incall-manager, react-native-interactive-image-gallery

README.md
This links to a blog post about the app, which itself links to the sourcecode
=> Added bristol pound

README.md
Along with it updated stars for ReactNative Seed & NativeBase
=> Added BuilderX tools in utilities

README.md
=> added react native template super

README.md
Hello, I've added a new video tutorial which helps in getting started with coding UIs from scratch.
=> Added a new Youtube tutorial

README.md
Add rn-displayable that only aims to conditionnally (array of rules or props) to display a component.
The usual equivalent to `return this.props.isTrue && <Text>Displayed !</Text>` but DRY :-)
https://github.com/mfrachet/rn-displayable
=> Add rn-displayable

README.md
The best large list component for React Native.(iOS & Android)
=> Add react-native-largelist

README.md
Just added react-native-td link, thanks!
=> Add react-native-td link

README.md
Add an article about automated delivery on CircleCI 2.0 with Fabric for Android
=> Add an article to Continuous Integration section

README.md
=> Add renote link

README.md
Hi @jondot,
I have updated README with below libraries. Can you please merge this, it will help developers to easily build great mobile apps:
- [react-native-spruce](https://github.com/prscX/react-native-spruce)
- [react-native-bottom-action-sheet](https://github.com/prscX/react-native-bottom-action-sheet)
- [react-native-iconic](https://github.com/prscX/react-native-iconic)
- [react-native-shine-button](https://github.com/prscX/react-native-shine-button)
- [react-native-download-button](https://github.com/prscX/react-native-download-button)
- [react-native-siri-wave-view](https://github.com/prscX/react-native-siri-wave-view)
- [react-native-popover-menu](https://github.com/prscX/react-native-popover-menu)
- [react-native-about-libraries](https://github.com/prscX/react-native-about-librari …
=> Added Support for React Native Libraries

README.md
I added React Native newsletters to the list :)
=> Added a section for React Native newsletters

README.md
=> Added Ueno's react-native-starter

README.md
https://github.com/FormidableLabs/react-native-app-auth
=> Add react-native-app-auth

README.md
=> react native scaling drawer

README.md
Added Reactor in the seeds list.
> https://github.com/Jerameel/Reactor
=> Added Reactor

README.md
Hi, I develop this package. And I wanted to share with more people. I hope you accept this PR.
[https://github.com/talut/react-native-simple-card-view](https://github.com/talut/react-native-simple-card-view)
Also you can see my medium post about this package: [https://medium.com/@talut/react-native-simple-card-view-8a39ac83b1e0](https://medium.com/@talut/react-native-simple-card-view-8a39ac83b1e0)
Have a good day.
=> Add react-native-simple-card-view

README.md
Hi,
just created a highly customizable video player because I didn't found something highly extensible that fill my needs.
I share it with the community.
Best regards
=> Add React Native True Sight

README.md
Update the react native queue link and also added a link to a tutorial I wrote on how to use React Native Queue to manage periodic background tasks that run when app is closed.
=> Updating React Native Queue info.

README.md
A Third-party Hupu App (http://bbs.hupu.com/) client implemented using React Native (Android and iOS).
=> Add a Open Source React Native App

README.md
https://github.com/BhavanPatel/react-native-navbar-color
Module for change color of react-native footer navigation bar in android
=> Added react-native-navbar-color

README.md
I would like to add my library for helping community
=> Add 2 library: shimmer placeholder & timeline theme

README.md
Article "Wait… What Happens When my React Native Application Starts? — An In-depth Look Inside React Native"
=> Adding article to the Internals section

README.md
=> Add Magento React Native App

README.md
Hi,
First of all: Thank you for this great list. I really enjoy checking it out regularly.
In this pull request I added the React Native TypeScript template, which can seamlessly be used with the React Native CLI. It's consistent with the default React Native template and also supports Jest unit testing in TypeScript.
Thanks in common.
Emin
=> Added react-native-template-typescript

README.md
=> Add React Native Turbolinks

README.md
https://github.com/CompanyCam/react-native-walkthrough-tooltip
https://medium.com/companydev/calling-attention-to-new-features-in-our-react-native-app-ba0d1daa380
=> add react-native-walkthrough-tooltip

README.md
hello. 
I updated my pre module's (react-native-awesome-alert) star rating 
and introduced new one (react-native-responsive-fontsize)
=> updated pre package's star-rating and added react-native-responsive-fontsize

README.md
react-native-select-box has not JS code.
see https://github.com/akiran/react-native-select-box/blob/master/index.js
=> Add react-native-draggable-calendar and remove react-native-select-box

README.md
[react-native-tone](https://github.com/oliviachang29/react-native-tone) is a simple library for playing tones in React Native (iOS only).
=> Add react-native-tone to Media

README.md
* Move `react-native-animatable` from "UI" to "Animation" section
* Update stars
=> Move react-native-animatable

README.md
Hey there,
Thank you for this awesome project! While scanning through the list searching for something else I saw the `react-native-sensors` is missing, so I thought I add it real quick
=> add react-native-sensors

README.md
Hey friends! I think **styled-react-native** package would be good fit for this list :)
Thanks in advance
=> Add styled-react-native lib

README.md
The current section is outdated
=> Updated conference section with upcoming conferences

README.md
A pure JavaScript React-Native dialog that follows closely the UI of its native counterpart while expanding its features.
=> Add react-native-dialog

README.md
Prism is a library that returns a Higher Order Component (HOC) exposing access to a style registry containing user-defined colors, fonts and styles.
=> Add react-native-prism

README.md
Library for displaying PDF documents in react-native
=> Add react-native-view-pdf

README.md
React Native's Animated library reimplemented.
It provides a more comprehensive, low level abstraction for the Animated library API to be built on top of and hence allow for much greater flexibility especially when it comes to gesture based interactions.
=> Add react-native-reanimated

README.md
It's a hackable "rate us" component for React Native.
=> Added react-native-rate-modal

README.md
add emotionjs for styling in react-native
=>  add emotion for styling section

README.md
https://github.com/lvlrSajjad/react-native-fancy-carousel-viewpager
=> Added react-native-fancy-carousel-viewpager

README.md
https://github.com/lvlrSajjad/react-native-expandable-fab-menu
=> Added react-native-expandable-fab-menu

README.md
https://github.com/lvlrSajjad/react-native-rounded-navigation-drawer
=> Added react-native-rounded-navigation-drawer

README.md
https://github.com/lvlrSajjad/react-native-masonry-brick-list
=> Added react-native-masonry-brick-list

README.md
https://github.com/lvlrSajjad/react-native-blur-overlay
=> Added react-native-blur-overlay

README.md
Secure Storage for React Native (Android & iOS)
=> Added rn-secure-storage

README.md
WatermelonDB is a new way of dealing with user data in React Native and React web apps.
It's optimized for building complex applications in React / React Native, and the number one goal is real-world performance.
=> Add WatermelonDB

README.md
A date picker component for Android and iOS
=> Added react-native-date-picker

README.md
For more details check here: https://github.com/proyecto26/react-native-inappbrowser
=> Add new InAppBrowser plugin

README.md
Easy Responsive Grid Layout for React Native.
=> Add react-native-easy-grid

README.md
- Add React Native Paper by Callstack
- update RN Elements Stargazers count
=> Update Libraries Section

README.md
Add react-native-simple-slider to read-me file.
=> Add react-native-simple-slider to read-me file.

README.md
Galio is a brand new UI framework for React Native.
=> Add Galio UI Framework

README.md
Native file viewer for React Native. Preview any type of file supported by the mobile device.
[https://github.com/vinzscam/react-native-file-viewer](https://github.com/vinzscam/react-native-file-viewer)
=> Added react-native-file-viewer

README.md
I would like to add react-native-paper ui components library to this list. It's been really popular recently and I think it deserves to be on that list :)
=> Add react-native-paper library.

README.md
[react-native-cross-settings](https://github.com/aMarCruz/react-native-cross-settings) is a React Native `Settings` compatible module for both Android & iOS.
=> Adds react-native-cross-settings

README.md
=> Update README.md - add blog post

README.md
Animated Flatlist for React Native.
https://github.com/shakogegia/react-native-animated-flatlist
=> Animated flatlist

README.md
Add react-native-deep-link package.
=> Add react-native-deep-link package

README.md
Stylish puzzle adventure game. Done with React Native. Paid, no ads and no IAPs. Now open sourced, so free to play as long as you know how to run React Native app ;-)
https://www.hydropuzzle.com / https://github.com/hydropuzzle/hydropuzzle
=> Add Hydropuzzle game

README.md
Add [react-native-svg-transformer](https://github.com/kristerkari/react-native-svg-transformer) to the list.
=> Add react-native-svg-transformer

README.md
Hi, I added my 3 packages (react-native-countries | react-native-picker-module | rn-actionsheet-module)
=> react-native-countries | react-native-picker-module | rn-actionsheet-module  added

README.md
BinStorm is a React Native styling utility for rapidly building custom user interfaces.
=> Add binstorm in Styling

README.md
Starter Kit with Onboarding Screens (Welcome, Login, Registration), User Management with Firebase Auth and Facebook Login.
=> Adding React Native Starter Kit with Firebase & FB integration

README.md
A React Native draggable and sortable grid component write by typescript
=> react-native-draggable-grid

README.md
Adding https://github.com/OvalMoney/react-native-fitness under **"Integrations"**
=> Add react-native-fitness

README.md
Adding Lyrics King open source app.
=> Adding Lyrics King app

README.md
- Really light React-Native package to handle fallback when image is on error
- A small lib to test and learn how write lib with typescript
=> Add react-native-safe-image

README.md
This component help developer to create multiple selection from list with ease.
=> Added "react-native-select-multiple"

README.md
Add https://github.com/pvinis/rn-diff-purge
=> Add rn-diff-purge

README.md
Add react-native-sms-retriever at System section.
=> react-native-sms-retriever (System)

README.md
Update amount of stars for specific github repos.
=> Update Github stars

README.md
=> Add react-native-boundary

.github/PULL_REQUEST_TEMPLATE.md
I watch this repo, and I am interested in every addition.
The problem is that I need to go and check the PR code and copy the link and paste it into my browser.
It would be nice and easy if contributors added a link also to the PR description.
=> add a pr template.

README.md
Add react-native-bouncing-ball UI component
=> Add react-native-bouncing-ball UI component

README.md
See full documentation for this component [here](https://github.com/jonsamp/react-native-header-scroll-view).
Gif of component:
=> adds react-native-header-scroll-view

README.md
Added a 'best practices' React article to the list.
https://buttercms.com/blog/best-practices-for-building-a-large-scale-react-application
=> Added a React Article

README.md
https://github.com/TVke/awesome-react-native#styling
=> Add react-native-tailwindcss to styling options

README.md
Add [react-int](https://github.com/leafOfTree/react-int): A simple way to use react/react-native with redux and redux-saga.
See also https://leafoftree.github.io/react-int/
=> Add react-int

README.md
[React Native Easy Starter - using  rn59, easy-peasy, hooks, codepush etc](https://github.com/HarishJangra/react-native-easy-starter)
=> react-native-easy-starter added

README.md
https://github.com/pankod/react-native-picker-modal-view
=> Added react-native-picker-modal-view package

README.md
PS: @jondot, if you need a hand keeping up with the PR's I'll be happy to spend 1-2h per week
=> remove AppHub as it is not longer active

README.md
https://github.com/tassdr/react-native-template
=> Add react-native-template to readme

README.md
[first-born] (https://github.com/99xt/first-born)
=> Add first-born to Framework category

README.md
Link: https://github.com/flaque/quirk
The app is a GPL licensed CBT app for folks fighting depression, anxiety, and other mental health disorders.
=> Add Quirk 🐙

README.md
A video/audio scrubber for react native.
=> Add react-native-scrubber library

README.md
I just add Appitr IDE
Appitr : [https://appitr.com/](https://appitr.com/)
Appitr IDE : [https://ide.appitr.com/](https://ide.appitr.com/)
Example Projects : [https://ide.appitr.com/projects](https://ide.appitr.com/projects)
Documentation : [https://docs.appitr.com/](https://docs.appitr.com/)
=> Add Appitr IDE.

README.md
Thanks! ;)
https://github.com/xcarpentier/rn-verifcode
=> Please add rn-verifcode.

README.md
- https://appjs.co/
- https://infinite.red/ChainReactConf
=> Add 2 upcoming conferences in 2019

README.md
https://github.com/Flipkart/recyclerlistview
Android Native RecyclerList implemented over React Native, very useful for heavy lists.
=> Add RecyclerList

README.md
- https://blog.jscrambler.com/build-a-chatbot-with-dialogflow-and-react-native/
- https://blog.jscrambler.com/create-a-react-native-image-recognition-app-with-google-vision-api/
- https://medium.com/swlh/using-styled-components-with-react-native-de645fcf4787
- https://medium.com/crowdbotics/how-to-build-a-real-time-logo-detection-app-with-react-native-google-vision-api-and-crowdbotics-9ed65fbcd15
- https://medium.com/crowdbotics/how-to-build-a-news-reader-app-with-react-native-and-newsapi-8508f48f2b43
- https://medium.com/crowdbotics/21-useful-open-source-packages-for-react-native-807f65a818a1?source=---------9------------------
=> Add 6 Articles

README.md
https://github.com/alexfoxy/react-native-units
=> Added react-native-units to utils

README.md
Here are the links:
https://github.com/IjzerenHein/react-native-magic-move
https://github.com/IjzerenHein/react-navigation-magic-move
cheers!
=> Added react-native-magic-move & react-navigation-magic-move

README.md
Blog with RN articles -> https://ideamotive.co/blog/category/react-native/
=> Adds Ideamotive blog

README.md
* Almost perfect switch on react-native
* Have a good peformance on both iOS and Android  
* Add gesture with `PanResponder`  
* More animations to follow iOS native performance
* Support async and sync event
* Support bidirectional data binding
* Clear code style
=> add react-native-switch-pro library

README.md
https://github.com/heyman333/react-native-iphone-se-helper
Always feel thanksful you for your effort👍
=> describe react-native-iphone-se-helper

README.md
Add [react-native-agora](https://github.com/syanbo/react-native-agora) to the list.
=> adds react-native-agora

README.md
[github.com/react-native-really-awesome-button](https://github.com/rcaferati/react-native-really-awesome-button)
=> Add react-native-really-awesome-button

README.md
https://github.com/budiadiono/react-native-calculator
=> Added react-native-calculator

README.md
https://github.com/xcarpentier/react-native-suggester
=> Add react-native-suggester

README.md
=> Added Red Shift blog

README.md
[React Native Animated Loader](https://github.com/vikrantnegi/react-native-animated-loader)
=> Add react-native-animated-loader

README.md
Adding https://github.com/colbymillerdev/react-native-progress-steps under the "UI" section.
=> Adding react-native-progress-steps.

README.md
Add new project - Library for testing React Native UI components and screens, [pixels-catcher](https://www.npmjs.com/package/pixels-catcher)
=> New project pixels-catcher

README.md
https://github.com/xcarpentier/react-native-suggester
=> fix rn-suggester

README.md
https://github.com/tomLadder/react-native-echarts-wrapper
=> Update README.md (Add react-native-echarts-wrapper)

README.md
added react-native-hide-modal
https://github.com/heyman333/react-native-hide-modal
=> add react-native-hide-modal

README.md
https://github.com/busfor/react-native-apay
=> add react-native-apay

README.md
https://github.com/busfor/react-native-google-pay
=> add react-native-google-pay

README.md
* plus minor formatting proposals
=> Syntax issue on paragraph 272

README.md
[Awesome React Native Boilerplates](https://github.com/appitr/awesome-react-native-boilerplates)
Effective start for your development with the most popular react-native navigation and UI libraries
=> Add Awesome React Native Boilerplates.

README.md
Toast feedback messages for React Native
https://github.com/MAKARD/react-native-toastboard
https://snack.expo.io/@makard/react-native-toastboard
=> Add react-native-toastboard

README.md
Complex form builder. 
https://github.com/MAKARD/react-native-formawesome
https://snack.expo.io/@makard/react-native-formawesome
=> Add react-native-formawesome

README.md
https://github.com/mxmzb/react-native-gesture-detector
=> Add react-native-gesture-detector

README.md
https://github.com/Cherrypick-Consulting/react-native-android-video
=> Add the react-native-android-video library

README.md
https://github.com/ge6285790/react-native-sortable-gridview
=> Add the react-native-sortable-gridview lib

README.md
Add 14 new articles on React Native development.
=> Add new articles

README.md
Add 2 upcoming conferences for React Native
=> Add 2 upcoming conferences for React Native

README.md
add a good internationalization resource
https://github.com/facebookincubator/fbt
=> add a good internationalization resource

README.md
https://github.com/tsepeti/react-native-dots-pagination
=> add react-native-dots-pagination

README.md
Added react-native-template-airbnb (Flow, Prettier integration)
https://github.com/iboldurev/react-native-template-airbnb (https://www.npmjs.com/package/react-native-template-airbnb)
=> Added react-native-template-airbnb

README.md
also changing the link to purge from the initial one i made, to the link of the moved repo in react-native-community.
https://github.com/react-native-community/upgrade-helper
https://react-native-community.github.io/upgrade-helper/
https://github.com/react-native-community/rn-diff-purge
=> adding the upgrade helper tool

README.md
This PR references [react-native-eva-icons](https://github.com/artyorsh/react-native-eva-icons).
Thank you for the great list 👍
=> Add react-native-eva-icons

README.md
=> add react-hook-hooker

README.md
Adding action-sheet-rn (https://github.com/mfrachet/action-sheet-rn) which is a declarative way to define an ActionSheet in react native
+ update of my rn-placeholder star count 😇
=> adding action-sheet-rn

README.md
List of beautiful loading animations for React Native
=> Add "react-native-loader-kit"

README.md
Expose iPad mouse & track pads interactions to React Native
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jondot/awesome-react-native/1003)
=> Add `react-native-pointer-interactions`

README.md
=> Add react-native boilerplate with typescript 

README.md
https://github.com/underscopeio/react-native-navigation-hooks
=> Add react-native-navigation-hooks

README.md
https://github.com/peacechen/react-native-modal-selector
=> Add react-native-modal-selector

README.md
https://github.com/amaurymartiny/shoot-i-smoke/
[rendered](https://github.com/amaurymartiny/awesome-react-native/tree/patch-2#open-source-apps)
=> Add Sh**t! I Smoke

README.md
react-native-root-siblings: Add sibling elements after your app root element. The created sibling elements are above the rest of your app elements. This can be used to create a Modal component or something should be over your app.
=> Add " react-native-root-siblings"

README.md
* `apps .Instabug`  --> `apps. Instabug`
=> Minor formatting proposal on paragraph 63

README.md
https://github.com/react-hook-form/react-hook-form
=> Added "react-hook-form" in Forms

README.md
Added @arelstone/react-native-email-chip to UI section
[@arelstone/react-native-email-chip](https://github.com/arelstone/react-native-email-chip)
=> Added @arelstone/react-native-email-chip

README.md
A set of layout components for building RN views blazingly fast ⚡, and with debug mode and design system grid you can investigate non-trivial visual issues.
https://github.com/mobily/stacks
https://mobily.github.io/stacks/
=> Stacks: a set of layout components for building RN views blazingly fast ⚡

README.md
https://github.com/seniv/react-native-notifier
=> Add "react-native-notifier"

README.md
https://www.npmjs.com/package/react-native-ultimate-config
=> Add `react-native-ultimate-config`

README.md
https://github.com/chende008/react-native-fast-app
=> add react-native-fast-app

README.md
A Cross Platform(Android & iOS) ActionSheet with a flexible api, native performance and zero dependency code for react native. Create anything you want inside ActionSheet.
https://github.com/ammarahm-ed/react-native-actions-sheet
=> add react-native-actions-sheet

README.md
Add [NMF.earth](https://github.com/NotMyFaultEarth/nmf-app) app : calculate, understand and reduce your carbon footprint. 
Available for Android and iOS, using Expo, Redux Toolkit and Typescript.
=> Add NMF.earth app

README.md
Blog post about "React Native: Native Modules made for React developers — On the developer experience with 3rd-party libraries for RN 0.60+"
=> Add article "React Native: Native Modules made for React developers"

README.md
=> Update README.md - Add react-native-mov-to-mp4

README.md
[`react-native-photoeditorsdk`](https://www.npmjs.com/package/react-native-photoeditorsdk) and [`react-native-videoeditorsdk`](https://www.npmjs.com/package/react-native-videoeditorsdk) are the official React Native integrations for the native PhotoEditor SDK and VideoEditor SDK.
=> Add react-native-photoeditorsdk and react-native-videoeditorsdk

README.md
https://github.com/heyman333/react-native-responsive-fontSize
=> Increase star count of react-native-responsive-fontSize

README.md
* [react-native-image-modal ★16](https://github.com/dev-yakuza/react-native-image-modal) -  simple full size modal image for iOS and Android. supports zoom-in/out, double-tap zoom-in/out, move and swipe-to-dismiss
=> add react-native-image-modal

README.md
https://github.com/codypearce/react-native-material-drawer by @codypearce
=> Add react-native-material-drawer

README.md
[react-native-animated-math ★54](https://github.com/rastapasta/react-native-animated-math) - An Animated API math extension - implements sin, cos, tan and pow as Animated Nodes with full Native Driver support
=> Add react-native-animated-math

README.md
https://github.com/yonahforst/react-native-community-maps
=> add react-native-community-maps

README.md
https://github.com/gomjellie/react-native-timetable
=> add react-native-timetable

README.md
https://github.com/tuantvk/monalisa-ui
=> Add new library monalisa-ui for UI component

README.md
=> Link to Build Development had one dash too many

README.md
https://github.com/jeanverster/react-native-styled-toast
=> add react-native-styled-toast

README.md
=> add reacteurope conference

README.md
=> add start react native animation series

README.md
Added [Intercom](https://github.com/tinycreative/react-native-intercom) lib
=> add intercom lib

README.md
=> change lib to the correct name and update stars

README.md
Added react-native-calendar-events
https://github.com/wmcmahan/react-native-calendar-events
=> Added react-native-calendar-events

README.md
https://github.com/mohebifar/react-native-easy-dnd
=> Add react-native-easy-dnd

README.md
https://github.com/EkoLabs/react-native-background-downloader
=> Add react-native-background-downloader

README.md
React Native Wizard
Easy, convenient, quick-forming Wizard component for React Native. 
[https://github.com/talut/react-native-wizard](https://github.com/talut/react-native-wizard)
=> Added react-native-wizard

README.md
=> Add React Native Modern Datepicker

README.md
add  [`radio-buttons-react-native`](https://github.com/sramezani/radio-buttons-react-native)
=> add radio-buttons-react-native

README.md
Added a new article link to the how-to section.
https://invertase.io/blog/getting-started-with-cloud-firestore-on-react-native
=> Added new how to

README.md
=> Add much component to readme.

README.md
https://github.com/CBCNewMedia/react-native-airplay-button
=> Add react-native-airplay-button

README.md
I have added react-native-scrollview-header in the UI list
https://github.com/weifxn/react-native-scrollview-header
=> Add react-native-scrollview-header to UI list

README.md
https://github.com/sarmad1995/react-native-easy-content-loader
React native light weight content loader.
=> REFACTOR: updated react-native-easy-content-loader stars

README.md
=> Add react-native-pure-navigation-bar

README.md
Library for making Facebook Chat like bubble (android only).
=> add floating bubble lib

README.md
=> Update React Native Boilerplate position and stars

README.md
• Add gif to Instabug section
• Modify content
=> Update Instabug listing

README.md
React Native module to help you with easily and highly customizable flashbars, top notifications or alerts.
Tried this library, it is very easy in use. Really liked it👍
https://github.com/lucasferreira/react-native-flash-message#readme
=> Add react-native-flash-message

README.md
=> Adding Artsy app.

README.md
[Chitthi](https://play.google.com/store/apps/details?id=com.wolfpack.chitthi&hl=en_SG) app to create beautiful old style postcards
=> add "post card app"

README.md
Open source tool for finding i18n keys in JavaScript/TypeScript projects. We use it in our Expo/React-Native app and ReactWeb to manage translations 👍
https://github.com/simplelocalize/simplelocalize-cli
=> Add SimpleLocalize CLI

README.md
https://github.com/react-native-community/fetch
=> Add react-native-fetch-api

README.md
https://github.com/acostalima/react-native-test-runner
=> Add react-native-test-runner

README.md
https://apps.apple.com/us/app/zudvpn-personal-vpn-on-cloud/id1517610454
https://github.com/zudvpn/ZudVPN
https://www.zudvpn.com
=> Add ZudVPN to Open Source Apps list

README.md
https://github.com/aykutkardas/react-icomoon
=> Added React-Icomoon.

README.md
https://react-native-elements.js.org
=> Add React Native Elements Playground

README.md
https://github.com/robertherber/react-native-telegraph
=> Added react-native-telegraph

README.md
https://github.com/robertherber/eslint-config-kingstinct-react-native
=> Added eslint-config-kingstinct-react-native

README.md
Adds an entry:
* [react-native-blob-courier](https://github.com/edeckers/react-native-blob-courier) - Efficiently download and upload blobs on native thread
=> Add react-native-blob-courier

README.md
Add [OsmiCSX](https://github.com/OsmiCSX/osmicsx) - An utility React Native style framework for rapidly building custom user interfaces.
=> Add OsmiCSX

README.md
GithubLink : https://github.com/c19354837/react-native-system-setting
=> Added react-native-system-setting

README.md
https://github.com/fasky-software/react-native-widgetkit
=> Added react-native-widgetkit

README.md
=> Add Bugfender to integrations

README.md
=> Added statek state management library

README.md
Hey @jondot 
just removing a dead link.
Cheers!
=> Removing dead how-to

README.md
https://github.com/AmitM30/react-native-typescript-boilerplate
An opinionated React Native Starter Kit with React Native Navigation v3 + Redux + Thunk to build iOS / Android apps using TypeScript
=> Add new repo link to Seeds section

README.md
Colibri is front-end framework created to build cross platform Android & iOS mobile apps using ready to use generic components of React Native. It contains a set of general purpose UI components styled in a similar way. Here is the [link](https://github.com/nidorx/react-native-colibri).
=> Add colibri

README.md
This package is a wrapper for the Onfido Library. Here is the [link](https://github.com/React-Native-Nation/react-native-onfido).
=> Add onfido

README.md
Here I've added native-based logs for React Native. Here is the [link](https://github.com/JessicaYeh/react-native-native-log).
=> add native logs

README.md
https://github.com/artxty/typed-async-storage
=> Add 'typed-async-storage'

README.md
https://github.com/ravirupareliya/rn-in-app-review
=> added rn-in-app-review

README.md
Added Nyxo (Open source sleep tracker built with React Native)
=> Add Nyxo to open source apps

README.md
- react-native-audio => no longer maintained
- react-native-community/react-native-audio-toolkit => same tools than previous one, easier to implement and with extra functionality (online read of audio file)
=> Update readme with react native audio toolkit

README.md
Github: https://github.com/N1ghtly/react-native-responsive-linechart
Docs & examples: http://react-native-responsive-linechart.surge.sh
=> Add react-native-responsive-linechart

README.md
RNStarter: https://github.com/i-mighty/RNStarter
=> Added RNStarter

README.md
We've written an article comparing Flutter and React Native to help folks think through which approach fits them best when building a mobile app.  The article suggests what approach may be best depending you the project requirements and experience level. https://buttercms.com/blog/flutter-vs-react-native-choosing-your-approach.
https://buttercms.com/blog/flutter-vs-react-native-choosing-your-approach
=> React Native vs Flutter comparison article

README.md
* [React Native Twitter Clone](https://www.cosmicjs.com/apps/react-native-twitter-clone) - React Native Twitter Clone powered by the Cosmic Headless CMS. [Read about how it was built](https://www.cosmicjs.com/blog/how-to-make-a-simple-twitter-clone-with-react-native).
Thank you! 🙏
=> Added Twitter Clone article

README.md
https://github.com/phuochau/react-native-360-image-viewer
=> Added react-native-360-image-viewer

README.md
Hi all! Adding a link to this new LevelDB binding for React Native: https://github.com/andymatuschak/react-native-leveldown
=> Adding react-native-leveldown

README.md
Add [mrousavy/react-native-google-nearby-messages](https://github.com/mrousavy/react-native-google-nearby-messages) to **Components -> System**
=> Add react-native-google-nearby-messages

README.md
Add react-native-blurhash in [UI](./README.md#Components) (https://github.com/mrousavy/react-native-blurhash)
=> Add react-native-blurhash

README.md
Added [Appcircle](https://appcircle.io/) CI/CD tool
=> Add Appcircle CI/CD tool

README.md
https://github.com/alexbrazier/react-native-network-logger
<p float="left" align="center">
</p>
=> Add react-native-network-logger

README.md
=> Fix link to Build & Development

README.md
https://github.com/chende008/react-native-easy-app
Now that the star data has risen to 207, could you change it when you commit?
=> rename react-native-fast-app to react-native-easy-app

README.md
Chain React 2019 playlist on youtube
=> add link for Chain React 2019

README.md
https://shift.infinite.red/nsfw-js-for-react-native-a37c9ba45fe9
=> Add link to NSFWJS in React Native article

README.md
An ambitious, heavily tested rich text library.
https://github.com/typeskill/typer
=> Add @typeskill/typer

README.md
https://github.com/chende008/react-native-easy-app
Update stars count
=> Update stars count for react-native-easy-app
